### ISSUE TITLE
Create-React-Native-App

### ISSUE THREAD

**Issue by thebetterjort** [dwicao/react-universal-rendering#1]
This is a great repo. Many thanks. Unfortunately, I do not have the ability to run the android/ios emulators on my computer. Using the create-react-native-app allows me to run the code on my device through expo. Any thoughts on how to get this hooked up?

**Comment by dwicao** [comment]
@thebetterjort actually you could run on your real devices
Anyway, I thinks it's possible
most of any cases, you only need to move the web project folder and the webpack configuration
and change component import from `primitives`

**Comment by UADACID** [comment]
@dwicao ini ada rencana di bkin package sendiri?
